package ir.buildingcharge.app;

import android.content.ContentResolver;
import android.content.ContentValues;
import android.net.Uri;
import android.os.Build;
import android.os.Environment;
import android.provider.MediaStore;
import android.util.Base64;
import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import java.io.OutputStream;

/**
 * Generated by scripts/apply-android-branding.mjs from resources/android/java — do not edit in android/.
 *
 * Saves a PNG (base64) to the gallery in Pictures/<album> through MediaStore.
 * Android 10+ (API 29+): scoped storage, NO storage permission needed; the image shows up in the gallery immediately.
 * Android 9 and older would need the legacy storage write permission, which the app does not request: rejects with code UNSUPPORTED
 * (the JS side then opens the share sheet instead).
 */
@CapacitorPlugin(name = "GallerySaver")
public class GallerySaverPlugin extends Plugin {

    @PluginMethod
    public void saveImage(PluginCall call) {
        String data = call.getString("data");
        String fileName = sanitize(call.getString("fileName", "apartemant.png"));
        String album = sanitize(call.getString("album", "Apartemant"));
        if (data == null || data.isEmpty()) {
            call.reject("No image data", "NO_DATA");
            return;
        }
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) {
            call.reject("Saving to the gallery without storage permission requires Android 10+", "UNSUPPORTED");
            return;
        }
        int comma = data.indexOf(',');
        if (data.startsWith("data:") && comma > 0) data = data.substring(comma + 1);

        byte[] bytes;
        try {
            bytes = Base64.decode(data, Base64.DEFAULT);
        } catch (IllegalArgumentException e) {
            call.reject("Invalid base64 data", "BAD_DATA");
            return;
        }

        ContentResolver resolver = getContext().getContentResolver();
        ContentValues values = new ContentValues();
        values.put(MediaStore.Images.Media.DISPLAY_NAME, fileName);
        values.put(MediaStore.Images.Media.MIME_TYPE, "image/png");
        values.put(MediaStore.Images.Media.RELATIVE_PATH, Environment.DIRECTORY_PICTURES + "/" + album);
        values.put(MediaStore.Images.Media.IS_PENDING, 1);

        Uri uri = null;
        try {
            uri = resolver.insert(MediaStore.Images.Media.getContentUri(MediaStore.VOLUME_EXTERNAL_PRIMARY), values);
            if (uri == null) throw new IllegalStateException("MediaStore insert returned null");
            try (OutputStream out = resolver.openOutputStream(uri)) {
                if (out == null) throw new IllegalStateException("Cannot open output stream");
                out.write(bytes);
            }
            ContentValues done = new ContentValues();
            done.put(MediaStore.Images.Media.IS_PENDING, 0);
            resolver.update(uri, done, null, null);

            JSObject ret = new JSObject();
            ret.put("uri", uri.toString());
            ret.put("path", Environment.DIRECTORY_PICTURES + "/" + album + "/" + fileName);
            call.resolve(ret);
        } catch (Exception e) {
            if (uri != null) {
                try {
                    resolver.delete(uri, null, null);
                } catch (Exception ignored) {
                    // ignore
                }
            }
            call.reject("Saving image failed: " + e.getMessage(), "SAVE_FAILED", e);
        }
    }

    private static String sanitize(String s) {
        if (s == null) return "apartemant";
        String out = s.replaceAll("[\\\\/:*?\"<>|]", "_").trim();
        return out.isEmpty() ? "apartemant" : out;
    }
}
