package ir.buildingcharge.app;

import android.graphics.Color;
import android.os.Bundle;
import androidx.activity.EdgeToEdge;
import androidx.activity.SystemBarStyle;
import com.getcapacitor.BridgeActivity;

/**
 * Generated by scripts/apply-android-branding.mjs from resources/android/java — do not edit in android/.
 *
 * Edge-to-edge on every Android version (not only Android 15+ where the OS enforces it):
 * Capacitor 8's SystemBars plugin (insetsHandling: 'css' + viewport-fit=cover, WebView 140+) passes the
 * real status/navigation bar sizes to the page as --safe-area-inset-*, assuming the WebView is drawn
 * behind the system bars. On Android 14 and older the window was NOT edge-to-edge, so the system already
 * kept the content above the navigation bar and the CSS padding was applied a second time (empty band
 * under the bottom tab bar). Making the window edge-to-edge everywhere keeps both sides consistent.
 */
public class MainActivity extends BridgeActivity {
    /** Dark scrim only used on Android 7.x where dark navigation-bar icons are not supported. */
    private static final int LEGACY_SCRIM = Color.argb(0x80, 0x1b, 0x1b, 0x1b);

    @Override
    public void onCreate(Bundle savedInstanceState) {
        registerPlugin(GallerySaverPlugin.class);
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(
            this,
            SystemBarStyle.light(Color.TRANSPARENT, LEGACY_SCRIM),
            SystemBarStyle.light(Color.TRANSPARENT, LEGACY_SCRIM)
        );
    }
}
