package ir.buildingcharge.app;

import android.app.Activity;
import android.content.Context;
import android.os.Bundle;
import android.os.CancellationSignal;
import android.os.ParcelFileDescriptor;
import android.print.PageRange;
import android.print.PrintAttributes;
import android.print.PrintDocumentAdapter;
import android.print.PrintDocumentInfo;
import android.print.PrintManager;
import android.util.Base64;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;

/**
 * Generated by scripts/apply-android-branding.mjs from resources/android/java — do not edit in android/.
 *
 * Hands a ready-made PDF (base64, image-only pages built offline in JS) to the Android print framework
 * (PrintManager + PrintDocumentAdapter). No permission is needed: the system print dialog is shown by the OS.
 * Rejects with PRINT_FAILED when printing cannot start; the JS side then falls back to the share sheet.
 */
@CapacitorPlugin(name = "ReportPrint")
public class ReportPrintPlugin extends Plugin {

    @PluginMethod
    public void printPdf(final PluginCall call) {
        String data = call.getString("data");
        final String jobName = call.getString("jobName", "Apartemant");
        if (data == null || data.isEmpty()) {
            call.reject("No PDF data", "NO_DATA");
            return;
        }
        int comma = data.indexOf(',');
        if (data.startsWith("data:") && comma > 0) data = data.substring(comma + 1);
        final byte[] bytes;
        try {
            bytes = Base64.decode(data, Base64.DEFAULT);
        } catch (IllegalArgumentException e) {
            call.reject("Invalid base64 data", "BAD_DATA");
            return;
        }
        final Activity activity = getActivity();
        if (activity == null) {
            call.reject("No activity", "PRINT_FAILED");
            return;
        }
        activity.runOnUiThread(new Runnable() {
            @Override
            public void run() {
                try {
                    PrintManager pm = (PrintManager) activity.getSystemService(Context.PRINT_SERVICE);
                    if (pm == null) {
                        call.reject("Print service not available", "PRINT_FAILED");
                        return;
                    }
                    pm.print(jobName, new PdfAdapter(bytes, jobName), new PrintAttributes.Builder().build());
                    call.resolve();
                } catch (Exception e) {
                    call.reject("Printing failed: " + e.getMessage(), "PRINT_FAILED", e);
                }
            }
        });
    }

    /** Streams the in-memory PDF to the print spooler. */
    private static class PdfAdapter extends PrintDocumentAdapter {
        private final byte[] bytes;
        private final String name;

        PdfAdapter(byte[] bytes, String name) {
            this.bytes = bytes;
            this.name = name.replaceAll("[\\\\/:*?\"<>|]", "_") + ".pdf";
        }

        @Override
        public void onLayout(PrintAttributes oldAttributes, PrintAttributes newAttributes, CancellationSignal cancellationSignal, LayoutResultCallback callback, Bundle extras) {
            if (cancellationSignal.isCanceled()) {
                callback.onLayoutCancelled();
                return;
            }
            PrintDocumentInfo info = new PrintDocumentInfo.Builder(name)
                .setContentType(PrintDocumentInfo.CONTENT_TYPE_DOCUMENT)
                .setPageCount(PrintDocumentInfo.PAGE_COUNT_UNKNOWN)
                .build();
            callback.onLayoutFinished(info, true);
        }

        @Override
        public void onWrite(PageRange[] pages, ParcelFileDescriptor destination, CancellationSignal cancellationSignal, WriteResultCallback callback) {
            try (OutputStream out = new FileOutputStream(destination.getFileDescriptor())) {
                out.write(bytes);
                out.flush();
                callback.onWriteFinished(new PageRange[] { PageRange.ALL_PAGES });
            } catch (IOException e) {
                callback.onWriteFailed(e.getMessage());
            }
        }
    }
}
