/**
 * ساخت خودکار استایل حالت تاریک از روی global.css (بدون وابستگی خارجی).
 * برای هر قاعده‌ای که رنگ دارد، یک قاعده با پیشوند `:root[data-theme="dark"]` می‌سازد که فقط
 * ویژگی‌های رنگی را با معادل تاریک (src/logic/darkColor.ts) بازنویسی می‌کند.
 * اجرا: npm run theme:generate  (خروجی: src/styles/dark.generated.css؛ تست مطمئن می‌شود همگام است.)
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { darkenCssValue, hasCssColor } from '../src/logic/darkColor.ts';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const SRC_CSS = path.join(ROOT, 'src/styles/global.css');
export const OUT_CSS = path.join(ROOT, 'src/styles/dark.generated.css');
const DARK = ':root[data-theme="dark"]';
/** ویژگی‌هایی که سفید در آن‌ها «متن/آیکون روی زمینه رنگی» است و نباید به رنگ کارت تبدیل شود */
const KEEP_WHITE = new Set(['color', 'fill', 'stroke', '-webkit-text-fill-color', 'caret-color']);

/** جدا کردن اعلان‌ها در سطح بالا (; داخل پرانتز مثل url(data:...) نادیده گرفته می‌شود) */
function splitDecls(body) {
  const out = []; let depth = 0, cur = '';
  for (const ch of body) {
    if (ch === '(') depth++;
    if (ch === ')') depth--;
    if (ch === ';' && depth === 0) { out.push(cur); cur = ''; } else cur += ch;
  }
  if (cur.trim()) out.push(cur);
  return out.map((d) => d.trim()).filter(Boolean);
}
function splitSelectors(sel) {
  const out = []; let depth = 0, cur = '';
  for (const ch of sel) {
    if (ch === '(' || ch === '[') depth++;
    if (ch === ')' || ch === ']') depth--;
    if (ch === ',' && depth === 0) { out.push(cur.trim()); cur = ''; } else cur += ch;
  }
  if (cur.trim()) out.push(cur.trim());
  return out;
}
const darkSelector = (s) => (s === ':root' ? DARK : s.startsWith(':root') ? DARK + s.slice(5) : `${DARK} ${s}`);

const isWhite = (v) => /^(#fff(fff)?|white|rgba?\(\s*255\s*,\s*255\s*,\s*255\s*(,\s*1)?\))$/i.test(v.trim());

function darkRule(selectorText, body) {
  const decls = [];
  const all = splitDecls(body).map((d) => [d.slice(0, d.indexOf(':')).trim().toLowerCase(), d.slice(d.indexOf(':') + 1).trim().replace(/\s*!important\s*$/i, '')]);
  // قاعده‌ای که متن سفید دارد: زمینه رنگی آن به‌اندازه‌ای تیره می‌شود که متن سفید خوانا بماند
  const whiteText = all.some(([p, v]) => p === 'color' && isWhite(v));
  for (const d of splitDecls(body)) {
    const i = d.indexOf(':');
    if (i < 0) continue;
    const prop = d.slice(0, i).trim().toLowerCase();
    const val = d.slice(i + 1).trim();
    if (!hasCssColor(val)) continue;
    const important = /!important\s*$/i.test(val);
    const clean = val.replace(/\s*!important\s*$/i, '');
    decls.push(`${prop}: ${darkenCssValue(clean, KEEP_WHITE.has(prop), whiteText && prop.startsWith('background'))}${important ? ' !important' : ''};`);
  }
  if (decls.length === 0) return '';
  return `${splitSelectors(selectorText).map(darkSelector).join(',\n')} { ${decls.join(' ')} }\n`;
}

/** پردازش متن CSS (قاعده‌های ساده + @media تو در تو؛ @keyframes/@font-face نادیده گرفته می‌شود) */
function walk(css) {
  let out = ''; let i = 0;
  while (i < css.length) {
    const open = css.indexOf('{', i);
    if (open < 0) break;
    const head = css.slice(i, open).trim();
    let depth = 1, j = open + 1;
    while (j < css.length && depth > 0) { if (css[j] === '{') depth++; else if (css[j] === '}') depth--; j++; }
    const body = css.slice(open + 1, j - 1);
    if (head.startsWith('@media') || head.startsWith('@supports')) {
      const inner = walk(body);
      if (inner) out += `${head} {\n${inner}}\n`;
    } else if (!head.startsWith('@')) {
      out += darkRule(head, body);
    }
    i = j;
  }
  return out;
}

export function generateDarkCss(cssText) {
  const noComments = cssText.replace(/\/\*[\s\S]*?\*\//g, '');
  return `/* AUTO-GENERATED by scripts/dark-css.mjs from global.css — do not edit (npm run theme:generate) */\n${walk(noComments)}`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const css = generateDarkCss(fs.readFileSync(SRC_CSS, 'utf8'));
  fs.writeFileSync(OUT_CSS, css, 'utf8');
  console.log(`[dark-css] wrote ${path.relative(ROOT, OUT_CSS)} (${css.length} chars)`);
}
