/**
 * ساخت خودکار استایل پالت‌های تم روشن (از ۱.۶.۱۳) از روی global.css.
 * «آسمانی» همان global.css است (بدون خروجی). برای هر پالت دیگر، همهٔ قاعده‌های رنگی با پیشوند
 * `:root[data-theme="light"][data-light="<id>"]` دوباره نوشته می‌شوند (کامل، نه فقط تفاوت‌ها: این پیشوند از هر
 * قاعدهٔ حالت‌دار global.css قوی‌تر است و اگر قاعده‌ای جا بیفتد، اولویت ترتیب قواعد به هم می‌خورد).
 * اجرا: npm run theme:generate  (خروجی: src/styles/light.generated.css؛ تست مطمئن می‌شود همگام است.)
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { hasCssColor } from '../src/logic/darkColor.ts';
import { lightenCssValue } from '../src/logic/lightColor.ts';
import { LIGHT_PALETTES, LIGHT_PALETTE_ORDER } from '../src/logic/lightPalettes.ts';
import { splitDecls, emit, isWhite, KEEP_WHITE, isStateSelector, VAR_COLOR_PROPS } from './dark-css.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const SRC_CSS = path.join(ROOT, 'src/styles/global.css');
export const OUT_CSS = path.join(ROOT, 'src/styles/light.generated.css');
const LIGHT = ':root[data-theme="light"]';
/** متغیرهای رنگ پُرِ دکمه‌ها/نشان‌ها (متن سفید روی آن‌ها) در :root */
const FILL_VARS = new Set(['--primary', '--primary-press', '--success', '--success-press', '--danger']);

function lightDecls(body, palette, keepVars = false) {
  const decls = [];
  const all = splitDecls(body).map((d) => [d.slice(0, d.indexOf(':')).trim().toLowerCase(), d.slice(d.indexOf(':') + 1).trim().replace(/\s*!important\s*$/i, '')]);
  const whiteText = all.some(([p, v]) => p === 'color' && isWhite(v));
  for (const d of splitDecls(body)) {
    const i = d.indexOf(':');
    if (i < 0) continue;
    const prop = d.slice(0, i).trim().toLowerCase();
    const val = d.slice(i + 1).trim();
    if (!hasCssColor(val)) {
      if (keepVars && VAR_COLOR_PROPS.has(prop) && /var\(/.test(val)) decls.push(`${prop}: ${val}`);
      continue;
    }
    const important = /!important\s*$/i.test(val);
    const clean = val.replace(/\s*!important\s*$/i, '');
    decls.push(`${prop}: ${lightenCssValue(clean, KEEP_WHITE.has(prop), (whiteText && prop.startsWith('background')) || FILL_VARS.has(prop), palette)}${important ? ' !important' : ''}`);
  }
  return decls;
}

function collect(css, palette, media = null, out = []) {
  let i = 0;
  while (i < css.length) {
    const open = css.indexOf('{', i);
    if (open < 0) break;
    const head = css.slice(i, open).trim();
    let depth = 1, j = open + 1;
    while (j < css.length && depth > 0) { if (css[j] === '{') depth++; else if (css[j] === '}') depth--; j++; }
    const body = css.slice(open + 1, j - 1);
    if (head.startsWith('@media') || head.startsWith('@supports')) collect(body, palette, head, out);
    else if (!head.startsWith('@')) {
      const decls = lightDecls(body, palette, isStateSelector(head));
      if (decls.length) out.push({ media, selector: head, decls });
    }
    i = j;
  }
  return out;
}

export function generateLightCss(cssText) {
  const noComments = cssText.replace(/\/\*[\s\S]*?\*\//g, '');
  let out = '/* AUTO-GENERATED by scripts/light-css.mjs from global.css — do not edit (npm run theme:generate) */\n';
  for (const id of LIGHT_PALETTE_ORDER) {
    const P = LIGHT_PALETTES[id];
    if (P.identity) continue;
    out += `\n/* ---- پالت روشن ${id}: ${P.name} ---- */\n${emit(collect(noComments, P), `${LIGHT}[data-light="${id}"]`)}`;
  }
  return out;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const css = generateLightCss(fs.readFileSync(SRC_CSS, 'utf8'));
  fs.writeFileSync(OUT_CSS, css, 'utf8');
  console.log(`[light-css] wrote ${path.relative(ROOT, OUT_CSS)} (${css.length} chars)`);
}
